[project]
name = "ex-gpt-stt-uv"
version = "0.1.0"
description = "Enhanced faster-whisper with Korean STT post-processing and meeting minutes generation"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "faster-whisper>=1.2.0",
    "requests>=2.32.5",
]
